FLAG_EVENT_CODES = {
    "event_defeat_falkner",
    "event_defeat_bugsy",
    "event_defeat_whitney",
    "event_defeat_monty",
    "event_defeat_chuck",
    "event_defeat_jasmine",
    "event_defeat_pryce",
    "event_defeat_clair",
    "event_clear_pokemon_league",
    "event_defeat_brock",
    "event_defeat_misty",
    "event_defeat_lt_surge",
    "event_defeat_erika",
    "event_defeat_janine",
    "event_defeat_sabrina",
    "event_defeat_blaine",
    "event_defeat_blue",
    "event_defeat_red"
}

HOSTED_VANILLA_CODES = {
    "bag",
    "beaconbadge",
    "bicycle",
    "coalbadge",
    "cobblebadge",
    "dawnstone",
    "daytime",
    "dowsingmachine",
    "dubiousdisc",
    "duskstone",
    "electirizer",
    "emeraldcartridge",
    "fenbadge",
    "fireredcartridge",
    "firestone",
    "forestbadge",
    "galactickey",
    "goodrod",
    "hm01cut",
    "hm02fly",
    "hm03surf",
    "hm04strength",
    "hm05whirlpool",
    "hm06rocksmash",
    "hm07waterfall",
    "hm08rockclimb",
    "iciclebadge",
    "kingsrock",
    "leafgreencartridge",
    "leafstone",
    "linkingcord",
    "magmarizer",
    "markingmap",
    "metalcoat",
    "minebadge",
    "moonstone",
    "nighttime",
    "oddkeystone",
    "oldcharm",
    "oldrod",
    "ovalstone",
    "parcel",
    "poffincase",
    "poketch",
    "protector",
    "radar",
    "razorclaw",
    "razorfang",
    "reapercloth",
    "relicbadge",
    "rubycartridge",
    "sapphirecartridge",
    "secretpotion",
    "shinystone",
    "ssticket",
    "suitekey",
    "sunstone",
    "superrod",
    "thunderstone",
    "tm70flash",
    "tm93rollout",
    "tm94ancientpower",
    "tm95doublehit",
    "tm96mimic",
    "upgrade",
    "waterstone",
    "workskey"
}

FLAG_ROADBLOCKS = {
    {flag="saw_route_210_barricade",        option="route_210_lower_barricade", hide_stage=26},
    {flag="saw_route_215_west_barricade",   option="route_215_barricade",       hide_stage=26},
    {flag="saw_route_207_barricade",        option="route_207_barricade",       hide_stage=16},
    {flag="saw_boat_canalave_snowpoint",    option="boat_canalave_snowpoint",   hide_stage=3},
    {flag="saw_boat_canalave_pastoria",     option="boat_canalave_pastoria",    hide_stage=3},
    {flag="saw_boat_pastoria_snowpoint",    option="boat_pastoria_snowpoint",   hide_stage=3},
    {flag="saw_pastoria_barriers",          option="pastoria_barriers",         hide_stage=2},
    {flag="saw_early_sunyshore",            option="early_sunyshore",           hide_stage=2},
}

FLAG_ITEM1_CODES = {
  {option="opt_overworld_off", codes={"reapercloth"}},
  {option="opt_badges_off", codes={"minebadge"}},
  {option="opt_hms_off", codes={"hm03surf"}},
  {option="opt_hidden_off", codes={"kingsrock"}},
  {option="opt_bicycle_off", codes={"bicycle"}},
  {option="opt_badges_off", codes={"forestbadge"}},
  {option="opt_hms_off", codes={"hm01cut"}},
  {option="opt_hidden_off", codes={"moonstone"}},
  {option="opt_npcgifts_off", codes={"upgrade"}},
  {option="opt_overworld_off", codes={"tm95doublehit"}},
  {option="opt_rods_off", codes={"superrod"}},
  {option="opt_overworld_off", codes={"leafstone"}},
  {option="opt_keyitems_off", codes={"workskey"}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
  {option="{}", codes={""}},
}
  
FLAG_ITEM2_CODES = {
  {option="{}", codes={""}},
  {option="opt_overworld_off", codes={"firestone"}},
  {option="opt_overworld_off", codes={"tm93rollout"}},
  {option="opt_overworld_off", codes={"dubiousdisc"}},
  {option="opt_hidden_off", codes={"razorclaw"}},
  {option="opt_keyitems_off", codes={"linkingcord"}},
  {option="opt_keyitems_off", codes={"galactickey"}},
  {option="opt_hidden_off", codes={"leafstone"}},
  {option="opt_badges_off", codes={"relicbadge"}},
  {option="opt_keyitems_off", codes={"poffincase"}},
  {option="opt_overworld_off", codes={"protector"}},
  {option="opt_overworld_off", codes={"shinystone"}},
  {option="opt_hms_off", codes={"hm04strength"}},
  {option="opt_npcgifts_off", codes={"metalcoat"}},
  {option="opt_overworld_off", codes={"metalcoat"}},
  {option="opt_keyitems_off", codes={"coupon_1"}},
  {option="opt_keyitems_off", codes={"coupon_2"}},
  {option="opt_keyitems_off", codes={"coupon_3"}},
  {option="opt_cartridges_off", codes={"fireredcartridge"}},
  {option="opt_cartridges_off", codes={"leafgreencartridge"}},
  {option="opt_poketchapps_off", codes={"poketch"}},
  {option="opt_cartridges_off", codes={"sapphirecartridge"}},
  {option="opt_overworld_off", codes={"dawnstone"}},
  {option="opt_hidden_off", codes={"sunstone"}},
  {option="opt_hidden_off", codes={"moonstone"}},
  {option="opt_overworld_off", codes={"tm96mimic"}},
  {option="opt_badges_off", codes={"coalbadge"}},
  {option="opt_hms_off", codes={"hm06rocksmash"}},
  {option="opt_hms_off", codes={"tm70flash"}},
  {option="opt_cartridges_off", codes={"emeraldcartridge"}},
  {option="opt_badges_off", codes={"fenbadge"}},
  {option="{}", codes={""}},
}

FLAG_ITEM3_CODES = {
  {option="opt_poketchapps_off", codes={"markingmap"}},
  {option="opt_poketchapps_off", codes={"dowsingmachine"}},
  {option="opt_npcgifts_off", codes={"oddkeystone"}},
  {option="opt_rods_off", codes={"goodrod"}},
  {option="opt_overworld_off", codes={"ovalstone"}},
  {option="opt_hidden_off", codes={"shinystone"}},
  {option="opt_keyitems_off", codes={"oldcharm"}},
  {option="opt_hidden_off", codes={"dawnstone"}},
  {option="opt_keyitems_off", codes={"suitekey"}},
  {option="opt_overworld_off", codes={"waterstone"}},
  {option="opt_overworld_off", codes={"magmarizer"}},
  {option="opt_hidden_off", codes={"razorfang"}},
  {option="opt_hms_off", codes={"hm08rockclimb"}},
  {option="opt_pokedex_off", codes={"pokedex_2"}},
  {option="opt_rods_off", codes={"oldrod"}},
  {option="opt_overworld_off", codes={"razorclaw"}},
  {option="opt_overworld_off", codes={"upgrade"}},
  {option="opt_overworld_off", codes={"dawnstone"}},
  {option="opt_overworld_off", codes={"dubiousdisc"}},
  {option="opt_hidden_off", codes={"leafstone"}},
  {option="opt_overworld_off", codes={"razorfang"}},
  {option="opt_overworld_off", codes={"protector"}},
  {option="opt_overworld_off", codes={"shinystone"}},
  {option="opt_overworld_off", codes={"reapercloth"}},
  {option="opt_hidden_off", codes={"thunderstone"}},
  {option="opt_hidden_off", codes={"waterstone"}},
  {option="opt_keyitems_off", codes={"radar"}},
  {option="opt_pokedex_off", codes={"pokedex_1"}},
  {option="opt_pokedex_off", codes={"pokedex_3"}},
  {option="opt_badges_off", codes={"iciclebadge"}},
  {option="opt_overworld_off", codes={"tm94ancientpower"}},
  {option="opt_hidden_off", codes={"firestone"}},
}

FLAG_ITEM4_CODES = {
  {option="opt_hidden_off", codes={"waterstone"}},
  {option="opt_hidden_off", codes={"thunderstone"}},
  {option="opt_hms_off", codes={"hm05whirlpool"}},
  {option="opt_timeitems_off", codes={"nighttime"}},
  {option="opt_hidden_off", codes={"firestone"}},
  {option="opt_badges_off", codes={"beaconbadge"}},
  {option="opt_hms_off", codes={"hm07waterfall"}},
  {option="opt_overworld_off", codes={"thunderstone"}},
  {option="opt_overworld_off", codes={"upgrade"}},
  {option="opt_hidden_off", codes={"oddkeystone"}},
  {option="opt_keyitems_off", codes={"parcel"}},
  {option="opt_ssticket_off", codes={"ssticket"}},
  {option="opt_bag_off", codes={"bag"}},
  {option="opt_hidden_off", codes={"unownfile_a"}},
  {option="opt_hidden_off", codes={"unownfile_b"}},
  {option="opt_hidden_off", codes={"unownfile_c"}},
  {option="opt_hidden_off", codes={"unownfile_d"}},
  {option="opt_hidden_off", codes={"unownfile_e"}},
  {option="opt_hidden_off", codes={"unownfile_ex"}},
  {option="opt_hidden_off", codes={"unownfile_f"}},
  {option="opt_hidden_off", codes={"unownfile_g"}},
  {option="opt_hidden_off", codes={"unownfile_h"}},
  {option="opt_hidden_off", codes={"unownfile_i"}},
  {option="opt_hidden_off", codes={"unownfile_j"}},
  {option="opt_hidden_off", codes={"unownfile_k"}},
  {option="opt_hidden_off", codes={"unownfile_l"}},
  {option="opt_hidden_off", codes={"unownfile_m"}},
  {option="opt_hidden_off", codes={"unownfile_n"}},
  {option="opt_hidden_off", codes={"unownfile_o"}},
  {option="opt_hidden_off", codes={"unownfile_p"}},
  {option="opt_hidden_off", codes={"unownfile_q"}},
  {option="opt_hidden_off", codes={"unownfile_qu"}},
}

FLAG_ITEM5_CODES = {
  {option="opt_hidden_off", codes={"unownfile_r"}},
  {option="opt_hidden_off", codes={"unownfile_s"}},
  {option="opt_hidden_off", codes={"unownfile_t"}},
  {option="opt_hidden_off", codes={"unownfile_u"}},
  {option="opt_hidden_off", codes={"unownfile_v"}},
  {option="opt_hidden_off", codes={"unownfile_w"}},
  {option="opt_hidden_off", codes={"unownfile_x"}},
  {option="opt_hidden_off", codes={"unownfile_y"}},
  {option="opt_hidden_off", codes={"unownfile_z"}},
  {option="opt_cartridges_off", codes={"rubycartridge"}},
  {option="opt_overworld_off", codes={"electirizer"}},
  {option="opt_keyitems_off", codes={"secretpotion"}},
  {option="opt_hidden_off", codes={"sunstone"}},
  {option="opt_overworld_off", codes={"duskstone"}},
  {option="opt_hms_off", codes={"hm02fly"}},
  {option="opt_badges_off", codes={"cobblebadge"}},
  {option="opt_overworld_off", codes={"razorclaw"}},
  {option="opt_overworld_off", codes={"duskstone"}},
  {option="opt_timeitems_off", codes={"daytime"}},
  {option="opt_hidden_off", codes={"duskstone"}},
}

UNOWN_ITEMS = {
    "unownfile_a", "unownfile_b", "unownfile_c", "unownfile_d",
    "unownfile_e", "unownfile_ex", "unownfile_f", "unownfile_g",
    "unownfile_h", "unownfile_i", "unownfile_j", "unownfile_k",
    "unownfile_l", "unownfile_m", "unownfile_n", "unownfile_o",
    "unownfile_p", "unownfile_q", "unownfile_qu", "unownfile_r",
    "unownfile_s", "unownfile_t", "unownfile_u", "unownfile_v",
    "unownfile_w", "unownfile_x", "unownfile_y", "unownfile_z"
}
