FLAG_EVENT_CODES = {
    "event_beat_sprout_tower",
    "event_burned_tower_disperse_legendary_dogs",
    "event_cerulean_meet_kanto_grunt",
    "event_cinnabar_island_blue_return_viridian",
    "event_clear_mahogany_hideout",
    "event_clear_pokemon_league",
    "event_clear_rocket_tower",
    "event_clear_slowpoke_well",
    "event_cure_amphy",
    "event_cure_miltank",
    "event_defeat_blaine",
    "event_defeat_blue",
    "event_defeat_brock",
    "event_defeat_bugsy",
    "event_defeat_chuck",
    "event_defeat_clair",
    "event_defeat_erika",
    "event_defeat_falkner",
    "event_defeat_janine",
    "event_defeat_jasmine",
    "event_defeat_lance_clair_dragons_den",
    "event_defeat_lt_surge",
    "event_defeat_misty",
    "event_defeat_morty",
    "event_defeat_pryce",
    "event_defeat_red",
    "event_defeat_sabrina",
    "event_defeat_whitney",
    "event_ecruteak_dance_theater_defeat_team_rocket",
    "event_elms_lab_get_master_ball",
    "event_farfetchd_rescue",
    "event_get_kenya",
    "event_get_mystery_egg",
    "event_get_togepi_egg",
    "event_give_kenya",
    "event_meet_ho_oh",
    "event_meet_lugia",
    "event_radio_quiz",
    "event_restore_power",
    "event_route_24_defeat_kanto_grunt", 
    "event_ruin_mistys_date",
    "event_shiny_gyarados",
    "event_talk_plant_manager",
    "event_talk_to_kurt",
    "event_defeated_rival_mount_moon",
    "event_get_hm08",
    "event_hear_about_missing_doll",
    "event_access_low_tide_dialogue",
}

HOSTED_VANILLA_CODES = {

}

FLAG_ROADBLOCKS = {

}

-- instructions from palex00:
-- search the name (e.g. "overworld_d45r0101_moon_stone") in https://github.com/ljtpetersen/hgss_archipelago/blob/devel/data_gen/locations.toml
-- check its type: overworld, hidden, hm, badge, key_item, npc_gift, rod, running_shoes, bicycle, pokedex, pokegear_card, various fly locations (https://github.com/ljtpetersen/hgss_archipelago/blob/22bdb082aed301849c7c76090f5bae42a63e4bf4/locations.py#L25-L69)
-- the option code you need to input is the option that code that needs to be true for this to work (so: if it's a hidden item, hidden_off)
-- the code is the item code of the item that this would turn on
-- leave the location name as a comment like in the examples so we can debug easier later

FLAG_ITEM1_CODES = {
  {option="opt_overworld_off",                      codes={"moonstone"}}, -- "overworld_d45r0101_moon_stone",
  {option="", codes={""}}, -- "overworld_t31_reaper_cloth",
  {option="", codes={""}}, -- "overworld_d39r0101_hm07",
  {option="", codes={""}}, -- "overworld_r42_dubious_disc",
  {option="", codes={""}}, -- "overworld_d46r0101_leaf_stone",
  {option="", codes={""}}, -- "overworld_d24r0212_oran_berry",
  {option="", codes={""}}, -- "overworld_d41r0102_dawn_stone",
  {option="", codes={""}}, -- "overworld_d24r0213_moon_stone",
  {option="", codes={""}}, -- "overworld_d22r0101_shiny_stone",
  {option="", codes={""}}, -- "overworld_d38r0103_dragon_scale",
  {option="", codes={""}}, -- "overworld_t09_magmarizer",
  {option="", codes={""}}, -- "overworld_d38r0102_protector",
  {option="", codes={""}}, -- "overworld_d11r0103_water_stone",
  {option="", codes={""}}, -- "overworld_d03r0103_dusk_stone",
  {option="", codes={""}}, -- "overworld_d03r0103_electirizer",
  {option="", codes={""}}, -- "overworld_d05r0102_oval_stone",
  {option="", codes={""}}, -- "hidden_w20_deepseascale",
  {option="", codes={""}}, -- "hidden_w20_deepseatooth",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_pallet"}}, -- "fly_map_pallet",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_viridian"}}, -- "fly_map_viridian",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_pewter"}}, -- "fly_map_pewter",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_cerulean"}}, -- "fly_map_cerulean",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_lavender"}}, -- "fly_map_lavender",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_vermilion"}}, -- "fly_map_vermilion",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_celadon"}}, -- "fly_map_celadon",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_fuchsia"}}, -- "fly_map_fuchsia",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_cinnabar_island"}}, -- "fly_map_cinnabar_island",
  {option="opt_randomize_fly_items_pokemon_league", codes={"fly_map_indigo_plateau"}}, -- "fly_map_indigo_plateau",
  {option="opt_randomize_fly_items_kanto",          codes={"fly_map_saffron"}}, -- "fly_map_saffron",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_new_bark"}}, -- "fly_map_new_bark",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_cherrygrove"}}, -- "fly_map_cherrygrove",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_violet"}}, -- "fly_map_violet",
}
  
FLAG_ITEM2_CODES = {
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_azalea"}}, -- "fly_map_azalea",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_cianwood"}}, -- "fly_map_cianwood",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_goldenrod"}}, -- "fly_map_goldenrod",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_olivine"}}, -- "fly_map_olivine",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_ecruteak"}}, -- "fly_map_ecruteak",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_mahogany"}}, -- "fly_map_mahogany",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_blackthorn"}}, -- "fly_map_blackthorn",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_lake_of_rage"}}, -- "fly_map_lake_of_rage",
  {option="opt_randomize_fly_items_mount_silver",   codes={"fly_map_mount_silver"}}, -- "fly_map_mount_silver",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_safari_zone_gate"}}, -- "fly_map_safari_zone_gate",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_battle_frontier"}}, -- "fly_map_battle_frontier",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_national_park"}}, -- "fly_map_national_park",
  {option="opt_randomize_fly_items_johto",          codes={"fly_map_victory_road_1f"}}, -- "fly_map_victory_road_1f",
  {option="opt_badges_off",                         codes={"fogbadge"}}, -- "ecruteak_badge_fog",
  {option="opt_badges_off",                         codes={"zephyrbadge"}}, -- "violet_badge_zephyr",
  {option="opt_badges_off",                         codes={"plainbadge"}}, -- "goldenrod_badge_plain",
  {option="opt_badges_off",                         codes={"mineralbadge"}}, -- "olivine_badge_mineral",
  {option="opt_badges_off",                         codes={"plainbadge"}}, -- "cianwood_badge_storm",
  {option="opt_badges_off",                         codes={"risingbadge"}}, -- "dragons_den_shrine_badge_rising",
  {option="opt_badges_off",                         codes={"hivebadge"}}, -- "azalea_badge_hive",
  {option="opt_badges_off",                         codes={"earthbadge"}}, -- "viridian_badge_earth",
  {option="opt_badges_off",                         codes={"glacierbadge"}}, -- "mahogany_badge_glacier",
  {option="opt_badges_off",                         codes={"hm01cut"}}, -- "ilex_forest_hm01",
  {option="opt_badges_off",                         codes={"hm02fly"}}, -- "cianwood_hm02",
  {option="opt_badges_off",                         codes={"hm03surf"}}, -- "ecruteak_dance_theater_hm03",
  {option="opt_badges_off",                         codes={"hm05whirlpool"}}, -- "route_42_hm04",
  {option="opt_badges_off",                         codes={"hm06rocksmash"}}, -- "team_rocket_headquarters_b2f_hm05",
  {option="opt_badges_off",                         codes={"hm07waterfall"}}, -- "route_36_hm06",
  {option="opt_badges_off",                         codes={"hm08rockclimb"}}, -- "pallet_town_oaks_lab_hm08",
  {option="opt_rods_off",                           codes={"oldrod"}}, -- "olivine_northwest_house_good_rod",
  {option="opt_rods_off",                           codes={"goodrod"}}, -- "route_32_pokemon_center_1f_old_rod",
  {option="opt_rods_off",                           codes={"superrod"}}, -- "route_12_fishing_brother_house_super_rod",
}

FLAG_ITEM3_CODES = {
  {option="opt_pokedex_off",                        codes={"pokedex_1"}}, -- "route_30_mr_pokemon_house_pokedex",
  {option="opt_pokedex_off",                        codes={"pokedex_2"}}, -- "ss_aqua_olivine_port_interior_pokedex",
  {option="opt_pokegearcards_off",                  codes={"upgradableradiopokegearcard_2"}}, -- "lavender_town_radio_station_radio",
  {option="opt_pokegearcards_off",                  codes={"upgradableradiopokegearcard_1"}}, -- "goldenrod_radio_tower_1f_radio",
  {option="", codes={""}}, -- "ecruteak_dowsing_machine_house_dowsing_mchn",
  {option="", codes={""}}, -- "new_bark_elms_lab_1f_ss_ticket",
  {option="", codes={""}}, -- "cianwood_pharmacy_secretpotion",
  {option="", codes={""}}, -- "d37r0105_cardkey",
  {option="", codes={""}}, -- "route_36_oran_berries",
  {option="", codes={""}}, -- "slowpoke_well_kings_rock",
  {option="", codes={""}}, -- "sprout_tower_tm70",
  {option="", codes={""}}, -- "t06_lost_item",
  {option="", codes={""}}, -- "t29_red_scale",
  {option="", codes={""}}, -- "goldenrod_squirtbottle",
  {option="", codes={""}}, -- "goldenrod_radio_tower_5f_basement_key",
  {option="", codes={""}}, -- "cerulean_machine_part",
  {option="", codes={""}}, -- "pewter_rainbow_wing",
  {option="", codes={""}}, -- "pewter_silver_wing",
  {option="", codes={""}}, -- "goldenrod_radio_tower_observation_deck_rainbow_wing",
  {option="", codes={""}}, -- "goldenrod_radio_tower_observation_deck_silver_wing",
  {option="", codes={""}}, -- "ecruteak_dance_theater_clear_bell",
  {option="", codes={""}}, -- "ecruteak_dance_theater_tidal_bell",
  {option="", codes={""}}, -- "mount_moon_square_clefairy_event_moon_stone",
  {option="", codes={""}}, -- "ss_aqua_metal_coat",
  {option="", codes={""}}, -- "route_25_sea_cottage_leaf_stone",
  {option="", codes={""}}, -- "route_25_sea_cottage_water_stone",
  {option="", codes={""}}, -- "route_25_sea_cottage_fire_stone",
  {option="", codes={""}}, -- "route_25_sea_cottage_thunderstone",
  {option="", codes={""}}, -- "saffron_silph_co_hq_upgrade",
  {option="", codes={""}}, -- "goldenrod_bike_shop_bicycle",
  {option="", codes={""}}, -- "mahogany_ragecandybar",
  {option="", codes={""}}, -- "saffron_copycat_house_2f_pass"
}