ITEM_MAPPING = {  
    -- HMs
	[16781] =   {{"tm70flash", "toggle"}},
	[420] =     {{"hm01cut", "progressive_toggle"}},
	[421] =     {{"hm02fly", "progressive_toggle"}},
	[16806] =   {{"hm03surf", "progressive_toggle"}},
	[423] =     {{"hm04strength", "progressive_toggle"}},
	[424] =     {{"hm05whirlpool", "progressive_toggle"}},
	[425] =     {{"hm06rocksmash", "progressive_toggle"}},
	[426] =     {{"hm07waterfall", "progressive_toggle"}},
	[427] =     {{"hm08rockclimb", "progressive_toggle"}},
    
    -- Badges
	[57344] =   {{"zephyrbadge", "toggle"}},
	[57345] =   {{"hivebadge", "toggle"}},
	[57346] =   {{"plainbadge", "toggle"}},
	[57347] =   {{"fogbadge", "toggle"}},
	[57348] =   {{"stormbadge", "toggle"}},
	[57349] =   {{"mineralbadge", "toggle"}},
	[57350] =   {{"glacierbadge", "toggle"}},
	[57351] =   {{"risingbadge", "toggle"}},
    [57352] =   {{"boulderbadge", "toggle"}},
    [57353] =   {{"cascadebadge", "toggle"}},
    [57354] =   {{"thunderbadge", "toggle"}},
    [57355] =   {{"rainbowbadge", "toggle"}},
    [57356] =   {{"soulbadge", "toggle"}},
    [57357] =   {{"marshbadge", "toggle"}},
    [57358] =   {{"volcanobadge", "toggle"}},
    [57359] =   {{"earthbadge", "toggle"}},
    
    -- Various Access Items
	[450] =     {{"bicycle", "toggle"}},
	[456] =     {{"ssticket", "toggle"}},
	[464] =     {{"secretpotion", "toggle"}},
	[20486] =   {{"dowsingmachine", "toggle"}},
    [477] =     {{"squirtbottle", "toggle"}},
    [16858] =   {{"clearbell", "toggle"}},
    [475] =     {{"cardkey", "toggle"}},
    [476] =     {{"basementkey", "toggle"}},
    [480] =     {{"pass", "toggle"}},
    [539] =     {{"hmreader", "toggle"}},
	[16539] =   {{"oranberry", "toggle"}},
	[5019] =    {{"oranberry", "toggle"}}, -- this is oran berry x3
	[478] =     {{"redscale", "toggle"}},
	[479] =     {{"lostitem", "toggle"}},
	[481] =     {{"machinepart", "toggle"}},
	[16866] =   {{"silverwing", "toggle"}},
	[16867] =   {{"rainbowwing", "toggle"}},
	[484] =     {{"mysteryegg", "toggle"}},
	[16887] =   {{"tidalbell", "toggle"}},
	[504] =     {{"ragecandybar", "toggle"}},
	[57371] =   {{"upgradableradiopokegearcard", "toggle"}},

    -- Encounter Related
	[445] =     {{"oldrod", "toggle"}},
	[446] =     {{"goodrod", "toggle"}},
	[447] =     {{"superrod", "toggle"}},
	[57368] =   {{"hoennsound", "toggle"}},
	[57369] =   {{"sinnohsound", "toggle"}},
    [57362] =   {{"morningtime", "toggle"}},
    [57363] =   {{"daytime", "toggle"}},
    [57364] =   {{"nighttime", "toggle"}},
	[57360] =   {{"upgradablepokedex", "progressive"}},
    
    -- Evolution Related
    [107]   = {{"shinystone", "toggle"}},
    [108]   = {{"duskstone", "toggle"}},
    [109]   = {{"dawnstone", "toggle"}},
    [16494] = {{"ovalstone", "toggle"}},
    [16605] = {{"kingsrock", "toggle"}},
    [16610] = {{"deepseatooth", "toggle"}},
    [16611] = {{"deepseascale", "toggle"}},
    [16617] = {{"metalcoat", "toggle"}},
    [16619] = {{"dragonscale", "toggle"}},
    [16636] = {{"upgrade", "toggle"}},
    [16705] = {{"protector", "toggle"}},
    [16706] = {{"electirizer", "toggle"}},
    [16707] = {{"magmarizer", "toggle"}},
    [16708] = {{"dubiousdisc", "toggle"}},
    [16709] = {{"reapercloth", "toggle"}},
    [16710] = {{"razorclaw", "toggle"}},
    [16711] = {{"razorfang", "toggle"}},
    [471]   = {{"linkingcord", "toggle"}},
    [80]    = {{"sunstone", "toggle"}},
    [81]    = {{"moonstone", "toggle"}},
    [82]    = {{"firestone", "toggle"}},
    [83]    = {{"thunderstone", "toggle"}},
    [84]    = {{"waterstone", "toggle"}},
    [85]    = {{"leafstone", "toggle"}},

	--Fly Unlocks
	[57372]    = {{"fly_map_pallet", "toggle"}},
    [57373]    = {{"fly_map_viridian", "toggle"}},
    [57374]    = {{"fly_map_pewter", "toggle"}},
    [57375]    = {{"fly_map_cerulean", "toggle"}},
    [57376]    = {{"fly_map_lavender", "toggle"}},
    [57377]    = {{"fly_map_vermillion", "toggle"}},
    [57378]    = {{"fly_map_celadon", "toggle"}},
    [57379]    = {{"fly_map_fuchsia", "toggle"}},
    [57380]    = {{"fly_map_cinnabar_island", "toggle"}},
	[57381]    = {{"fly_map_indigo_plateau", "toggle"}},
    [57382]    = {{"fly_map_saffron", "toggle"}},
    [57383]    = {{"fly_map_new_bark", "toggle"}},
    [57384]    = {{"fly_map_cherrygrove", "toggle"}},
    [57385]    = {{"fly_map_violet", "toggle"}},
    [57386]    = {{"fly_map_azalea", "toggle"}},
    [57387]    = {{"fly_map_cianwood", "toggle"}},
    [57388]    = {{"fly_map_goldenrod", "toggle"}},
    [57389]    = {{"fly_map_olivine", "toggle"}},
	[57390]    = {{"fly_map_ecruteak", "toggle"}},
    [57391]    = {{"fly_map_mahogany", "toggle"}},
    [57392]    = {{"fly_map_blackthorn", "toggle"}},
    [57393]    = {{"fly_map_lake_of_rage", "toggle"}},
    [57394]    = {{"fly_map_mount_silver", "toggle"}},
    [57395]    = {{"fly_map_safari_zone_gate", "toggle"}},
    [57396]    = {{"fly_map_battle_frontier", "toggle"}},
	[57397]    = {{"fly_map_national_park", "toggle"}},
    [57398]    = {{"fly_map_victory_road_1f", "toggle"}}
}
