ITEM_MAPPING = {  
	[16781] =   {{"tm70flash", "toggle"}},
	[420] =     {{"hm01cut", "progressive_toggle"}},
	[421] =     {{"hm02fly", "progressive_toggle"}},
	[16806] =   {{"hm03surf", "progressive_toggle"}},
	[423] =     {{"hm04strength", "progressive_toggle"}},
	[424] =     {{"hm05whirlpool", "progressive_toggle"}},
	[425] =     {{"hm06rocksmash", "progressive_toggle"}},
	[426] =     {{"hm07waterfall", "progressive_toggle"}},
	[427] =     {{"hm08rockclimb", "progressive_toggle"}},
--	[438] =     {{"workskey", "toggle"}},
--	[439] =     {{"oldcharm", "toggle"}},
--	[16824] =   {{"galactickey", "toggle"}},
	[445] =     {{"oldrod", "toggle"}},
	[446] =     {{"goodrod", "toggle"}},
	[447] =     {{"superrod", "toggle"}},
	[450] =     {{"bicycle", "toggle"}},
--	[451] =     {{"suitekey", "toggle"}},
	[456] =     {{"ssticket", "toggle"}},
--	[459] =     {{"parcel", "toggle"}},
--	[460] =     {{"coupons", "consumable"}},
--	[461] =     {{"coupons", "consumable"}},
--	[462] =     {{"coupons", "consumable"}},
--	[463] =     {{"storagekey", "toggle"}},
	[464] =     {{"secretpotion", "toggle"}},
	[57344] =   {{"zephyrbadge", "toggle"}},
	[57345] =   {{"hivebadge", "toggle"}},
	[57346] =   {{"plainbadge", "toggle"}},
	[57347] =   {{"fogbadge", "toggle"}},
	[57348] =   {{"stormbadge", "toggle"}},
	[57349] =   {{"mineralbadge", "toggle"}},
	[57350] =   {{"glacierbadge", "toggle"}},
	[57351] =   {{"risingbadge", "toggle"}},
    [57352] =   {{"boulderbadge", "toggle"}},
    [57353] =   {{"cascadebadge", "toggle"}},
    [57354] =   {{"thunderbadge", "toggle"}},
    [57355] =   {{"rainbowbadge", "toggle"}},
    [57356] =   {{"soulbadge", "toggle"}},
    [57357] =   {{"marshbadge", "toggle"}},
    [57358] =   {{"volcanobadge", "toggle"}},
    [57359] =   {{"earthbadge", "toggle"}},
--	[57346] =   {{"pokedex", "progressive"}},
--	[57347] =   {{"poketch", "toggle"}},
	[20486] =   {{"dowsingmachine", "toggle"}},
	[469] =     {{"marshpass", "toggle"}},
	[470] =     {{"unownfile", "consumable"}},
--	[57348] =   {{"bag", "toggle"}},
    [477] =     {{"squirtbottle", "toggle"}},
    [16858] =   {{"clearbell", "toggle"}},
    [475] =    {{"cardkey", "toggle"}},
    [476] =     {{"basementkey", "toggle"}},
    [480] =     {{"pass", "toggle"}},



    
    
    -- Access items
    [57362] = {{"morningtime", "toggle"}},
    [57363] = {{"daytime", "toggle"}},
    [57364] = {{"nighttime", "toggle"}},
    [539] =   {{"hmreader", "toggle"}},
    
    -- Encounter related
--    [57349] = {{"sapphirecartridge", "toggle"}},
--    [57350] = {{"rubycartridge", "toggle"}},
--    [57351] = {{"emeraldcartridge", "toggle"}},
--    [57352] = {{"fireredcartridge", "toggle"}},
--    [57353] = {{"leafgreencartridge", "toggle"}},
--    [431]   = {{"radar", "toggle"}},
--    [57356] = {{"treecamera", "toggle"}},
--    [57357] = {{"pokesonar", "toggle"}},
--    [16833] = {{"poffincase", "toggle"}},
--    [20492] = {{"markingmap", "toggle"}},
--    [16495] = {{"oddkeystone", "toggle"}},
--    [94]    = {{"honey", "toggle"}},
--    [4958]  = {{"honey", "toggle"}},
--    [6750]  = {{"honey", "toggle"}},
    
    -- Evolution related
--    [] = {{"tm93rollout", "toggle"}},
--    [] = {{"tm94ancientpower", "toggle"}},
--    [] = {{"tm95doublehit", "toggle"}},
--    [] = {{"tm96mimic", "toggle"}},
    [471] =   {{"linkingcord", "toggle"}},
    [16494] = {{"ovalstone", "toggle"}},
    [16605] = {{"kingsrock", "toggle"}},
    [16610] = {{"deepseatooth", "toggle"}},
    [16611] = {{"deepseascale", "toggle"}},
    [16617] = {{"metalcoat", "toggle"}},
    [16619] = {{"dragonscale", "toggle"}},
    [16636] = {{"upgrade", "toggle"}},
    [16705] = {{"protector", "toggle"}},
    [16706] = {{"electirizer", "toggle"}},
    [16707] = {{"magmarizer", "toggle"}},
    [16708] = {{"dubiousdisc", "toggle"}},
    [16709] = {{"reapercloth", "toggle"}},
    [16710] = {{"razorclaw", "toggle"}},
    [16711] = {{"razorfang", "toggle"}},
    [80]    = {{"sunstone", "toggle"}},
    [81]    = {{"moonstone", "toggle"}},
    [82]    = {{"firestone", "toggle"}},
    [83]    = {{"thunderstone", "toggle"}},
    [84]    = {{"waterstone", "toggle"}},
    [85]    = {{"leafstone", "toggle"}},
    [107]   = {{"shinystone", "toggle"}},
    [108]   = {{"duskstone", "toggle"}},
    [109]   = {{"dawnstone", "toggle"}},

	--Fly Unlocks
	[57372]    = {{"flyunlock_pallettown", "toggle"}},
    [57373]    = {{"flyunlock_viridiancity", "toggle"}},
    [57374]    = {{"flyunlock_pewtercity", "toggle"}},
    [57375]    = {{"flyunlock_ceruleancity", "toggle"}},
    [57376]    = {{"flyunlock_lavendertown", "toggle"}},
    [57377]    = {{"flyunlock_vermilioncity", "toggle"}},
    [57378]    = {{"flyunlock_celadoncity", "toggle"}},
    [57379]    = {{"flyunlock_fuchsiacity", "toggle"}},
    [57380]    = {{"flyunlock_cinnabarisland", "toggle"}},
	[57381]    = {{"flyunlock_indigoplateau", "toggle"}},
    [57382]    = {{"flyunlock_saffroncity", "toggle"}},
    [57383]    = {{"flyunlock_newbarktown", "toggle"}},
    [57384]    = {{"flyunlock_cherrygrovecity", "toggle"}},
    [57385]    = {{"flyunlock_violetcity", "toggle"}},
    [57386]    = {{"flyunlock_azaleatown", "toggle"}},
    [57387]    = {{"flyunlock_cianwoodcity", "toggle"}},
    [57388]    = {{"flyunlock_goldenrodcity", "toggle"}},
    [57389]    = {{"flyunlock_olivincity", "toggle"}},
	[57390]    = {{"flyunlock_ecruteakcity", "toggle"}},
    [57391]    = {{"flyunlock_mahoganytown", "toggle"}},
    [57392]    = {{"flyunlock_blackthorncity", "toggle"}},
    [57393]    = {{"flyunlock_lakeofrage", "toggle"}},
    [57394]    = {{"flyunlock_mountsilver", "toggle"}},
    [57395]    = {{"flyunlock_safarizonegate", "toggle"}},
    [57396]    = {{"flyunlock_battlefrontier", "toggle"}},
	[57397]    = {{"flyunlock_nationalpark", "toggle"}},
    [57398]    = {{"flyunlock_victoryroad", "toggle"}}
}
